Repository Dulce-Work-Schedule/2018.1-Dulce_App, pull requests merged in 2018-03, with the labels that each got.

#13 Adiciona arquivo equipe.md
  docs/equipe.md
Labels: EPS

#23 Fix #4 codigo conduta
  CODE_OF_CONDUCT.md
Labels: EPS, documento

#25 Fix #5
  CONTRIBUTING.md
  docs/img/commit-dupla.png
  docs/img/commit-individual.png
  docs/img/issue_example.gif
Labels: EPS, documento

#35 Fix #2 template_issue_pull_request
  docs/img/pull_request_template.png
  docs/issue_template.md
  docs/pull_request_template.md
Labels: EPS, documento

#44 HOTFIX #5 Modificando descrição de merge pra development
  CONTRIBUTING.md
Labels: EPS

#49 Development
  docs/equipe.md
Labels: EPS, MDS, documento, iniciante, manutenção, teste, treinamento

#58 Fix #56 Finalizando o Lexico
  docs/lexico.md
Labels: EPS, MDS, documento

#53 Fix #21_Criar_documento_de_visao
  docs/img/fishbone.png
  docs/img/mobi_saude.png
  docs/visao.md
Labels: EPS, MDS, documento, visao

#61 Fix #27 Criar Estrutura Analítica de Projetos (EAP)
  docs/eap.md
  docs/img/EAP.png
Labels: EPS, documento, escopo, intermediário, produto

#64 Fix #9 #10 #20 #21 #22 #27 #28 #29 #31 #34 #43 #54
  .DS_Store
  docs/.DS_Store
  docs/arquitetura.md
  docs/img/Diagrama-classes.png
  docs/img/arquitetura.png
  docs/img/diagrama.png
  docs/img/fishbone.png
  docs/img/mobi_saude.png
  docs/img/prototipo_baixa_fidelidade.png
  docs/img/reactdiagrama.png
  docs/prototipo.md
  docs/tap.md
  docs/visao.md
Labels: Arquitetura, Documento, EPS, Escopo, Evolução, História de Usuário, MDS, Manutenção, Protótipo, Treinamento, Visão

#63 Fix #59 hello word
  dulce/.babelrc
  dulce/.buckconfig
  dulce/.flowconfig
  dulce/.gitattributes
  dulce/.gitignore
  dulce/.watchmanconfig
  dulce/App.js
  dulce/__tests__/App.js
  dulce/android/app/BUCK
  dulce/android/app/build.gradle
  dulce/android/app/proguard-rules.pro
  dulce/android/app/src/main/AndroidManifest.xml
  dulce/android/app/src/main/java/com/dulce/MainActivity.java
  dulce/android/app/src/main/java/com/dulce/MainApplication.java
  dulce/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  dulce/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  dulce/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  dulce/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  dulce/android/app/src/main/res/values/strings.xml
  dulce/android/app/src/main/res/values/styles.xml
  dulce/android/build.gradle
  dulce/android/gradle.properties
  dulce/android/gradle/wrapper/gradle-wrapper.jar
  dulce/android/gradle/wrapper/gradle-wrapper.properties
  dulce/android/gradlew
  dulce/android/gradlew.bat
  dulce/android/keystores/BUCK
  dulce/android/keystores/debug.keystore.properties
  dulce/android/settings.gradle
  dulce/app.json
  dulce/index.js
  dulce/ios/dulce-tvOS/Info.plist
  dulce/ios/dulce-tvOSTests/Info.plist
  dulce/ios/dulce.xcodeproj/project.pbxproj
  dulce/ios/dulce.xcodeproj/xcshareddata/xcschemes/dulce-tvOS.xcscheme
  dulce/ios/dulce.xcodeproj/xcshareddata/xcschemes/dulce.xcscheme
  dulce/ios/dulce/AppDelegate.h
  dulce/ios/dulce/AppDelegate.m
  dulce/ios/dulce/Base.lproj/LaunchScreen.xib
  dulce/ios/dulce/Images.xcassets/AppIcon.appiconset/Contents.json
  dulce/ios/dulce/Images.xcassets/Contents.json
  dulce/ios/dulce/Info.plist
  dulce/ios/dulce/main.m
  dulce/ios/dulceTests/Info.plist
  dulce/ios/dulceTests/dulceTests.m
  dulce/package.json
Labels: EPS, ambiente

#84 Fix #30 Criar Roadmap
  docs/img/Roadmap.png
  docs/roadmap.md
Labels: Documento, EPS, feature, intermediário

#88 Fix #72 Estudo e definição da arquitetura do projeto
  docs/arquitetura.md
  docs/img/arquitetura.png
  docs/img/arquiteturaMicroservice.png
Labels: Arquitetura, Documento, EPS, Evolução, avançado

#89 Fix #65_refatoracao_doc_visao
  docs/img/fishbone.png
  docs/img/gestao_plus.jpg
  docs/lexico.md
  docs/visao.md
Labels: Documento, Evolução, MDS, Visão

#86 Fix #66_refatoracao_doc_arquitetura
  docs/arquitetura.md
  docs/img/Diagrama-classes.png
  docs/img/diagrama.png
  docs/img/diagrama1.png
  docs/img/diagramaUML1.png
Labels: Arquitetura, Documento, EPS, Evolução, MDS

#99 WIP: 68_editar_gestor
  dulce/App.js
  dulce/assets/img/logo.png
  dulce/src/Components/AGRButton.js
  dulce/src/Navigators/MainNavigator.js
  dulce/src/Screens/LoginScreen.js
  dulce/src/Screens/UsersScreen.js
Labels: EPS, MDS

#101 76 documento riscos
  docs/riscos.md
Labels: Documento, EPS, Viabilidade Técnica, projeto, riscos

#102 75 documentar os custos
  docs/EVM.md
  docs/tap.md
Labels: Avançado, Controle, Documento, EPS, custos, produto
