Repository Dulce-Work-Schedule/2018.1-Dulce_App, pull requests merged in 2018-04, with the labels that each got.

#110 Fix #67_prototipo
  docs/img/prototipo/.prototipo_holder
  docs/img/prototipo/1.1-login.png
  docs/img/prototipo/2.1-criar_Conta.png
  docs/img/prototipo/3.1-main.png
  docs/img/prototipo/4.1-perfil.png
  docs/img/prototipo/5.1-editarPerfil.png
  docs/img/prototipo/6.1-editarSenha.png
  docs/img/prototipo/DULCELOGOPROTO.png
  docs/img/prototipo/DULCEPROTO.ai
  docs/img/prototipo/dlcelogotype.ai
  docs/img/prototipo/dulcelogotype.png
  docs/protoio-DULCE.pdf
  docs/prototipo.md
Labels: Escopo, MDS, produto

#104 Fix #73 documentar metodologia
  docs/img/logos/GitHub.gif
  docs/img/logos/android.gif
  docs/img/logos/atom.png
  docs/img/logos/codeclimate.png
  docs/img/logos/docker.gif
  docs/img/logos/drive.gif
  docs/img/logos/graphql.png
  docs/img/logos/jest.png
  docs/img/logos/js.png
  docs/img/logos/mongodb.png
  docs/img/logos/node.png
  docs/img/logos/protoio.png
  docs/img/logos/slack.gif
  docs/img/logos/telegram.png
  docs/img/logos/travis.gif
  docs/img/papeis.png
  docs/metodologia.md
Labels: Avançado, Controle, Documento, EPS

#113 Fix #52 Documentar sprint
  docs/comunicacao.md
  docs/img/sprint/conhecimento_sprint_1.PNG
  docs/img/sprint/conhecimento_sprint_2.PNG
  docs/img/sprint/frequencia_commits_sprint_1.PNG
  docs/img/sprint/pareamento_sprint_2.PNG
  docs/img/sprint/velocity_sprint_2.PNG
  docs/riscos.md
  docs/sprints/sprint_1.md
  docs/sprints/sprint_2.md
Labels: Controle, Documento, EPS

#138 FIX #118 organizar docs
  CODE_OF_CONDUCT.md
  README.md
  docs/abertura/eap.md
  docs/abertura/tap.md
  docs/especificacao/arquitetura.md
  docs/especificacao/lexico.md
  docs/especificacao/protoio-DULCE.pdf
  docs/especificacao/prototipo.md
  docs/especificacao/roadmap.md
  docs/especificacao/visao.md
  docs/img/logos/android.gif
  docs/img/logos/facebook.gif
  docs/img/logos/node.png
  docs/img/logos/react-native.png
  docs/img/logos/whatsapp.png
  docs/img/logos/zenhub.png
  docs/img/sprint/burndown_sprint_2.PNG
  docs/viabilidade_tecnica/controle/EVM.md
  docs/viabilidade_tecnica/controle/riscos.md
  docs/viabilidade_tecnica/controle/sprints/sprint_0.md
  docs/viabilidade_tecnica/controle/sprints/sprint_1.md
  docs/viabilidade_tecnica/controle/sprints/sprint_10.md
  docs/viabilidade_tecnica/controle/sprints/sprint_2.md
  docs/viabilidade_tecnica/controle/sprints/sprint_3.md
  docs/viabilidade_tecnica/controle/sprints/sprint_4.md
  docs/viabilidade_tecnica/controle/sprints/sprint_5.md
  docs/viabilidade_tecnica/controle/sprints/sprint_6.md
  docs/viabilidade_tecnica/controle/sprints/sprint_7.md
  docs/viabilidade_tecnica/controle/sprints/sprint_8.md
  docs/viabilidade_tecnica/controle/sprints/sprint_9.md
  docs/viabilidade_tecnica/metodologia/metodologia.md
Labels: Controle, EPS, Scrum Master, projeto

#142 HOTFIX #120
  README.md
Labels: DevOps, Documento, EPS, Evolução, Iniciante, Task, Viabilidade Técnica, projeto

#144 WIP: Fix #81 Adicionando test coverage no travis CI
  .coveralls.yml
  .gitignore
  .travis.yml
  README.md
Labels: Ambiente, DevOps, DÉBITO TÉCNICO, EPS, Evolução, Infraestrutura, Intermediário, Task, Teste, Viabilidade Técnica, métricas, produto, projeto

#147 HOTFIX #81 Update readme
  README.md
Labels: Ambiente, BUG, DevOps, Documento, EPS, Infraestrutura, Iniciante, Task, Viabilidade Técnica, projeto

#145 WIP :#125 Criando Lista com perfis dos funcionários
  __tests__/ListScreen.test.js
  __tests__/__snapshots__/App.js.snap
  __tests__/__snapshots__/ListScreen.test.js.snap
  assets/img/calendarIcon.png
  package-lock.json
  src/Components/ScaleIcon.js
  src/Components/UserItem.js
  src/Navigators/MainNavigator.js
  src/Screens/ListScreen.js
  src/Screens/LoginScreen.js
  src/Screens/NewManager.js
  src/Screens/ProfileManagerScreen.js
  src/Screens/ProfileScreen.js
Labels: Evolução, História de Usuário, MDS

#178 Fix #174 Criando mind map de interação
  docs/especificacao/index.html
Labels: Documento, Escopo, PO, produto

#180 Fix #179 pre hooks
  .eslintrc
  .gitignore
  package.json
  utils/hooks/pre-commit
  utils/hooks/pre-push
  utils/install_hooks.sh
Labels: Ambiente, DevOps, EPS, Infraestrutura, Intermediário, Manutenção, React-Native, Task, Teste, Viabilidade Técnica, projeto

#182 HOTFIX #81
  README.md
Labels: Ambiente, BUG, DevOps, EPS, Infraestrutura, Iniciante, Manutenção, React-Native, Teste, Viabilidade Técnica, projeto

#176 FIX #158_documento_de_requisitos_de_qualidade
  docs/Documento_de_Requisito_de_Qualidade.md
  docs/assets/img/requisitosNaoFuncionais.png
  docs/especificacao/index.html
Labels: Documento, Especificação, Iniciante, MDS

#185 137 atualizar metodologia
  docs/abertura/index.html
  docs/viabilidade-tecnica/index.html
Labels: Controle, Documento, EPS, Intermediário, Manutenção, Scrum Master, Viabilidade Técnica, produto

#166 WIP: #154 aplicar axios
  __tests__/ListScreen.test.js
  package-lock.json
  src/Navigators/MainNavigator.js
  src/Screens/EditScreen.js
  src/Screens/EmployeeProfileScreen.js
  src/Screens/ListScreen.js
  src/Screens/LoginScreen.js
  src/Screens/NewManager.js
  src/Screens/ProfileManagerScreen.js
  src/Screens/ProfileScreen.js
  src/Screens/UsersScreen.js
Labels: MDS

#209 HOTFIX bugs refatoracao
  src/Navigators/MainNavigator.js
  src/Screens/EditScreen.js
  src/Screens/InitialScreen.js
  src/Screens/LoginScreen.js
  src/Screens/NewManager.js
Labels: BUG, HOTFIX

#212 Fix #211 HOTFIX Terminar correção de erros encontrados
  __tests__/Components/AGRButton.test.js
  __tests__/Components/SmallButton.test.js
  __tests__/Components/SmallLogo.test.js
  __tests__/Components/__snapshots__/AGRButton.test.js.snap
  __tests__/LoginScreen.test.js
  __tests__/NewManager.test.js
  __tests__/__snapshots__/App.js.snap
  __tests__/__snapshots__/EditScreen.test.js.snap
  __tests__/__snapshots__/ListScreen.test.js.snap
  __tests__/__snapshots__/LoginScreen.test.js.snap
  __tests__/__snapshots__/NewManager.test.js.snap
  __tests__/__snapshots__/ProfileManagerScreen.test.js.snap
  src/Components/BotaoTransparente.js
  src/Screens/EditScreen.js
  src/Screens/InitialScreen.js
  src/Screens/LoginScreen.js
  src/Screens/NewManager.js
  src/Screens/ProfileManagerScreen.js
Labels: BUG, HOTFIX, MDS

#215 Fix #188 remodelagem doc arquitetura
  docs/assets/img/Diagrama_pacotes_app.png
  docs/assets/img/Diagrama_pacotes_react.png
  docs/assets/img/ReactRedux.png
  docs/assets/img/diagrama_pacotes_api.png
  docs/especificacao/index.html
Labels: Arquitetura, Documento, MDS

#221 Fix #220 HOTFIX Trocar logo do aplicativo
  assets/img/DulceHorizontalFull.png
  assets/img/DulceHorizontalFull.svg
  assets/img/DulceLogoFull.png
  assets/img/DulceLogoFull.svg
  assets/img/DulceLogoSymbol.png
  assets/img/DulceLogoSymbol.svg
  src/Components/SmallLogo.js
  src/Screens/LoginScreen.js
Labels: 0-MDS, 1-Produto, 2-Design, HOTFIX

#226 HOTFIX #162 Modificando nome do app de 'dulce' para 'Dulce'
  android/app/src/main/res/values/strings.xml
  package.json
Labels: HOTFIX

#229 WIP:#192 adequar cobertura de testes
  __tests__/Components/ScaleIcon.test.js
  __tests__/Components/SmallButton.test.js
  __tests__/EditScreen.test.js
  __tests__/InitialScreen.test.js
  __tests__/LoginScreen.test.js
  __tests__/NewManager.test.js
  __tests__/__snapshots__/EditScreen.test.js.snap
  __tests__/__snapshots__/InitialScreen.test.js.snap
  src/Screens/EditScreen.js
  src/Screens/InitialScreen.js
  src/Screens/NewManager.js
  src/Screens/ProfileScreen.js
Labels: 0-MDS, 2-Teste, 5-Avançado, 5-Intermediário

#227 FIX #223 melhorias visuais
  App.js
  __tests__/InitialScreen.test.js
  __tests__/__snapshots__/InitialScreen.test.js.snap
  __tests__/__snapshots__/ListScreen.test.js.snap
  __tests__/__snapshots__/ProfileManagerScreen.test.js.snap
  package-lock.json
  package.json
  src/Components/routes.js
  src/Navigators/DoctorsNavigator.js
  src/Navigators/LoginNavigator.js
  src/Navigators/MainNavigator.js
  src/Navigators/NewManagerNavigator.js
  src/Navigators/ProfileNavigator.js
  src/Routes/Doctors.js
  src/Routes/Logout.js
  src/Routes/NewManager.js
  src/Routes/Profile.js
  src/Screens/EditScreen.js
  src/Screens/InitialScreen.js
  src/Screens/ListScreen.js
  src/Screens/LoginScreen.js
  src/Screens/NewManager.js
  src/Screens/ProfileManagerScreen.js
  src/Screens/ProfileScreen.js
Labels: 0-Developers, 0-MDS, 1-Produto, 2-Design, 2-Qualidade de Código, 5-Avançado

#233 FIX #232 Mudando para o link da API
  src/Screens/EditScreen.js
  src/Screens/ListScreen.js
  src/Screens/LoginScreen.js
  src/Screens/NewManager.js
  src/Screens/ProfileManagerScreen.js
  src/Screens/ProfileScreen.js
Labels: 0-MDS, 1-Infraestrutura, HOTFIX

#243 HOTFIX #192 adequar cobertura de testes
  __tests__/Actions/Actions.test.js
  __tests__/App.js
  __tests__/Reducers/ReducerCurrentUser.test.js
  __tests__/Routes/Doctors.test.js
  __tests__/Routes/NewManager.test.js
  __tests__/Routes/Profile.test.js
  __tests__/Routes/__snapshots__/Doctors.test.js.snap
  __tests__/Routes/__snapshots__/NewManager.test.js.snap
  __tests__/Routes/__snapshots__/Profile.test.js.snap
  __tests__/Screens/EditScreen.test.js
  __tests__/Screens/EmployeeProfileScreen.test.js
  __tests__/Screens/ListScreen.test.js
  __tests__/Screens/LoginScreen.test.js
  __tests__/Screens/NewManager.test.js
  __tests__/Screens/ProfileManagerScreen.test.js
  __tests__/Screens/ProfileScreen.test.js
  __tests__/Screens/__snapshots__/EditScreen.test.js.snap
  __tests__/Screens/__snapshots__/EmployeeProfileScreen.test.js.snap
  __tests__/Screens/__snapshots__/ListScreen.test.js.snap
  __tests__/Screens/__snapshots__/LoginScreen.test.js.snap
  __tests__/Screens/__snapshots__/NewManager.test.js.snap
  __tests__/Screens/__snapshots__/ProfileManagerScreen.test.js.snap
  __tests__/Screens/__snapshots__/ProfileScreen.test.js.snap
  __tests__/__snapshots__/App.js.snap
  src/Screens/EditScreen.js
  src/Screens/LoginScreen.js
Labels: 0-EPS, 0-MDS

#242 Fix #190 visualizar setores
  __tests__/__snapshots__/App.js.snap
  __tests__/__snapshots__/HospitalsScreen.test.js.snap
  __tests__/__snapshots__/SectorsScreen.test.js.snap
  src/Components/routes.js
  src/Navigators/HospitalsNavigation.js
  src/Navigators/SectorsNavigation.js
  src/Routes/Hospitals.js
  src/Routes/Sectors.js
  src/Screens/HospitalsScreen.js
  src/Screens/SectorsScreen.js
Labels: 0-Developers, 0-MDS, 1-Produto, 2-Feature, 5-Iniciante

#256 HOTFIX Desabilitando app transport security do IOS
  ios/dulce/Info.plist
Labels: BUG, HOTFIX

#264 Fix #203 Finalizando a documentação da sprint 5
  docs/assets/img/sprint/burndown_sprint_5.PNG
  docs/assets/img/sprint/pareamento_sprint_5.png
  docs/viabilidade-tecnica/index.html
  docs/viabilidade-tecnica/sprint/Sprint_5.html
Labels: 0-EPS, 0-Scrum Master, 1-Viabilidade Técnica, 2-Controle, 5-Intermediário

#251 Fix #247_Refatorando_documento_de_arquitetura.
  docs/assets/img/DiagramaDeClasse.png
  docs/assets/img/Diagrama_pacotes_app.png
  docs/assets/img/Diagrama_pacotes_react.png
  docs/assets/img/ReactRedux.png
  docs/assets/img/diagramaUML1.png
  docs/especificacao/arquitetura.html
Labels: 0-MDS, 1-Especificação, 2-Arquitetura, 2-GitHub Pages, 5-Intermediário
