Repository Dulce-Work-Schedule/2018.1-Dulce_App, pull requests merged in 2018-06, with the labels that each got.

#369 FIX #330 editar horario
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/WeekSchedule.test.js
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  android/app/src/main/res/values/styles.xml
  package.json
  src/Screens/WeekSchedule.js
Labels: 0-Developers, 1-Produto, 2-Feature, 3-História de Usuário, 4-Débito Técnico, 5-Intermediário

#373 HOTFIX #216 Adicionando clausula para evitar deploy em PRs
  .travis.yml
  utils/run_build_in_branch.sh
  utils/run_test_tag_version.sh
Labels: 0-DevOps, 1-Infraestrutura, 2-Deploy Contínuo, 2-Integração continua, 5-Iniciante

#395 Fix #356 testes 85%
  __mocks__/api_data.json
  __mocks__/axios.js
  __tests__/Components/ValidateButton.test.js
  __tests__/Components/__snapshots__/ListElements.test.js.snap
  __tests__/Routes/Doctors.test.js
  __tests__/Routes/__snapshots__/Doctors.test.js.snap
  __tests__/Routes/__snapshots__/Hospitals.test.js.snap
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Routes/__snapshots__/Sector.test.js.snap
  __tests__/Screens/EmployeeProfileScreen.test.js
  __tests__/Screens/HospitalsScreen.test.js
  __tests__/Screens/ListScreen.test.js
  __tests__/Screens/LoginScreen.test.js
  __tests__/Screens/ProfileManagerScreen.test.js
  __tests__/Screens/SectorsScreen.test.js
  __tests__/Screens/WeekSchedule.test.js
  __tests__/Screens/__snapshots__/HospitalsScreen.test.js.snap
  __tests__/Screens/__snapshots__/ListScreen.test.js.snap
  __tests__/Screens/__snapshots__/SectorsScreen.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Components/ListElements.js
  src/Components/ValidateButton.js
  src/Components/routes.js
  src/Navigators/DoctorsNavigator.js
  src/Navigators/NewManagerNavigator.js
  src/Navigators/SectorsNavigation.js
  src/Routes/Doctors.js
  src/Screens/EmployeeProfileScreen.js
  src/Screens/ListScreen.js
  src/Screens/ProfileManagerScreen.js
  src/Screens/ProfileScreen.js
Labels: 0-Developers, 1-Infraestrutura, 2-Teste, 3-Task, 4-Planejado, 5-Intermediário

#396 FIX #390 botao_login_social
  __tests__/Components/GoogleButton.test.js
  assets/img/google.png
  assets/img/logo.png
  src/Components/AGRButton.js
  src/Components/AGRInput.js
  src/Components/GoogleButton.js
  src/Screens/LoginScreen.js
Labels: 0-Developers, 1-Produto, 2-Feature, 3-História de Usuário, 4-Planejado, 5-Iniciante

#397 FIX #392_testes_week_schedule
  __tests__/Components/ListElements.test.js
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/WeekSchedule.test.js
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Screens/WeekSchedule.js
Labels: 0-Developers, 1-Produto, 2-Feature, 3-História de Usuário, 4-Planejado, 5-Intermediário

#399 FIX #381 solicitar férias
  __tests__/Components/DateRangePicker.test.js
  __tests__/Components/__snapshots__/AGRButton.test.js.snap
  __tests__/Components/__snapshots__/DateRangePicker.test.js.snap
  __tests__/Components/__snapshots__/GoogleButton.test.js.snap
  __tests__/Routes/__snapshots__/NewManager.test.js.snap
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/VacationScreen.test.js
  __tests__/Screens/__snapshots__/EditScreen.test.js.snap
  __tests__/Screens/__snapshots__/ListProfile.test.js.snap
  __tests__/Screens/__snapshots__/LoginScreen.test.js.snap
  __tests__/Screens/__snapshots__/NewManager.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  android/gradle/wrapper/gradle-wrapper.properties
  src/Components/AGRButton.js
  src/Components/DateRangePicker.js
  src/Components/GoogleButton.js
  src/Screens/VacationScreen.js
Labels: 0-Developers, 1-Produto, 2-Feature, 3-História de Usuário, 4-Planejado, 5-Intermediário

#434 Fix #412 Aplicando navegação para ListProfile
  src/Components/routes.js
  src/Navigators/ListProfileNavigator.js
  src/Routes/Profiles.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#443 [ci skip] Fix #431 doc metodologia
  docs/viabilidade-tecnica/index.html
  docs/viabilidade-tecnica/metodologia.html
  docs/viabilidade-tecnica/metricas_indicadores.html
  docs/viabilidade-tecnica/ritos_adotados.html
  docs/viabilidade-tecnica/sprint/sprint_6-15.html
Labels: 0-Scrum Master, 1-Produto, 2-Metodologia, 4-Planejado, 5-Intermediário

#436 FIX #410 Aplicando navegabilidade para tela de cadastro
  __tests__/Components/__snapshots__/DateRangePicker.test.js.snap
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/LoginScreen.test.js
  __tests__/Screens/__snapshots__/LoginScreen.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Navigators/LoginNavigator.js
  src/Screens/LoginScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#437 FIX #408 Navegabilidade_NewProfile
  __tests__/Components/__snapshots__/AGRInput.test.js.snap
  __tests__/Components/__snapshots__/ListElements.test.js.snap
  __tests__/Components/__snapshots__/ScreenHeader.test.js.snap
  __tests__/Routes/__snapshots__/Hospitals.test.js.snap
  __tests__/Routes/__snapshots__/NewManager.test.js.snap
  __tests__/Routes/__snapshots__/Profile.test.js.snap
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Routes/__snapshots__/Sector.test.js.snap
  __tests__/Screens/__snapshots__/EditScreen.test.js.snap
  __tests__/Screens/__snapshots__/HospitalsScreen.test.js.snap
  __tests__/Screens/__snapshots__/ListProfile.test.js.snap
  __tests__/Screens/__snapshots__/LoginScreen.test.js.snap
  __tests__/Screens/__snapshots__/NewManager.test.js.snap
  __tests__/Screens/__snapshots__/NewUser.test.js.snap
  __tests__/Screens/__snapshots__/NotificationScreen.test.js.snap
  __tests__/Screens/__snapshots__/ProfileManagerScreen.test.js.snap
  __tests__/Screens/__snapshots__/ProfileScreen.test.js.snap
  __tests__/Screens/__snapshots__/SectorsScreen.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Components/routes.js
  src/Navigators/ListProfileNavigator.js
  src/Routes/NewProfile.js
  src/Screens/ListProfile.js
  src/Screens/ProfileManagerScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#440 Fix #425 desconectar employee profile screen
  __tests__/Components/__snapshots__/DateRangePicker.test.js.snap
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/EmployeeProfileScreen.test.js
  __tests__/Screens/__snapshots__/EmployeeProfileScreen.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Screens/EmployeeProfileScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#438 FIX #432 desconectar hospital
  __tests__/Routes/Hospitals.test.js
  __tests__/Routes/__snapshots__/Hospitals.test.js.snap
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/HospitalsScreen.test.js
  __tests__/Screens/__snapshots__/HospitalsScreen.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Components/routes.js
  src/Navigators/HospitalsNavigation.js
  src/Routes/Hospitals.js
  src/Screens/HospitalsScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#439 FIX #429 desconectar NewManager
  __tests__/Routes/NewManager.test.js
  __tests__/Screens/NewManager.test.js
  src/Components/routes.js
  src/Navigators/NewManagerNavigator.js
  src/Routes/NewManager.js
  src/Screens/NewManager.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#441 FIX #426 desconectar sector screen
  __tests__/Routes/Sector.test.js
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Routes/__snapshots__/Sector.test.js.snap
  __tests__/Screens/SectorsScreen.test.js
  __tests__/Screens/__snapshots__/SectorsScreen.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Components/routes.js
  src/Navigators/HospitalsNavigation.js
  src/Navigators/SectorsNavigation.js
  src/Routes/Sectors.js
  src/Screens/SectorsScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#442 FIX #427 desconectar profile screen
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/ProfileScreen.test.js
  __tests__/Screens/__snapshots__/ProfileScreen.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Screens/ProfileScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#447 Fix #416 navegabilidade abono
  src/Components/routes.js
  src/Navigators/AbsencesNavigator.js
  src/Routes/Absences.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#445 FIX #419 Ligando tela com a api em produçao
  src/Screens/ProfileManagerScreen.js
Labels: 0-Developers, 1-Produto, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#457 Fix #456 alert login
  App.js
  ios/dulce.xcodeproj/project.pbxproj
  src/Components/GoogleButton.js
  src/Screens/LoginScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#459 FIX #458 Arrumando styles do login
  src/Components/AGRInput.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Iniciante

#463 Fix #462 text botoes
  src/Components/Absences.js
  src/Components/SignUpButton.js
  src/Screens/EditScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-História de Usuário, 5-Intermediário

#465 FIX #464 Arrumando botão aceitar
  src/Screens/NotificationScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#476 FIX #469 alert telas
  __tests__/Screens/AbsencesScreen.test.js
  __tests__/Screens/ListProfile.test.js
  src/Components/Absences.js
  src/Screens/AbsencesScreen.js
  src/Screens/NotificationScreen.js
Labels: 0-Developers, 1-Produto, 2-Feature, 3-História de Usuário, 4-Planejado, 5-Iniciante

#477 FIX #472 melhorar lista perfil
  src/Screens/ListProfile.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#478 FIX #471 componentizar styles
  __tests__/Components/__snapshots__/Absences.test.js.snap
  __tests__/Components/__snapshots__/DateRangePicker.test.js.snap
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/__snapshots__/AbsencesScreen.test.js.snap
  __tests__/Screens/__snapshots__/ListProfile.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Components/AGRButton.js
  src/Components/AGRInput.js
  src/Components/Absences.js
  src/Components/GoogleButton.js
  src/Components/IconButton.js
  src/Components/ScaleIcon.js
  src/Components/ScheduleItem.js
  src/Components/ScreenHeader.js
  src/Components/SideMenu.js
  src/Components/SignUpButton.js
  src/Components/SmallButton.js
  src/Components/SmallLogo.js
  src/Components/UserItem.js
  src/Components/ValidateButton.js
  src/Components/styles.js
  src/Screens/EditScreen.js
  src/Screens/ListProfile.js
  src/Screens/LoginScreen.js
  src/Screens/NewProfile.js
  src/Screens/NewUser.js
  src/Screens/NotificationScreen.js
  src/Screens/ProfileManagerScreen.js
  src/Screens/VacationScreen.js
  src/Screens/WeekSchedule.js
  src/Screens/styles.js
  src/styles.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#484 FIX #483 cobertura testes
  __tests__/Components/Absences.test.js
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/LoginScreen.test.js
  __tests__/Screens/NotificationScreen.test.js
  __tests__/Screens/WeekSchedule.test.js
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Teste, 3-Task, 4-Planejado, 5-Intermediário

#481 FIX #346 redux logout
  __tests__/Reducers/ReducerCurrentUser.test.js
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Components/SideMenu.js
  src/Reducers/currentUser.js
  src/Screens/InitialScreen.js
  src/Screens/LoginScreen.js
  src/Screens/ProfileManagerScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Avançado

#485 Fix #473 Adicionando botão de voltar das páginas secundárias
  __tests__/Components/ScreenHeader.test.js
  __tests__/Screens/EditScreen.test.js
  __tests__/Screens/NewUser.test.js
  src/Components/ScreenHeader.js
  src/Screens/EditScreen.js
  src/Screens/NewProfile.js
  src/Screens/NewUser.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#487 Fix #486 aplicando id visual
  __tests__/Components/SignUpButton.test.js
  __tests__/Components/__snapshots__/AGRButton.test.js.snap
  __tests__/Components/__snapshots__/Absences.test.js.snap
  __tests__/Components/__snapshots__/DateRangePicker.test.js.snap
  __tests__/Components/__snapshots__/IconButton.test.js.snap
  __tests__/Components/__snapshots__/ListElements.test.js.snap
  __tests__/Components/__snapshots__/ScreenHeader.test.js.snap
  __tests__/Components/__snapshots__/SideMenu.test.js.snap
  __tests__/Components/__snapshots__/SignUpButton.test.js.snap
  __tests__/Routes/__snapshots__/Profile.test.js.snap
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/NewUser.test.js
  __tests__/Screens/ProfileManagerScreen.test.js
  __tests__/Screens/__snapshots__/AbsencesScreen.test.js.snap
  __tests__/Screens/__snapshots__/EditScreen.test.js.snap
  __tests__/Screens/__snapshots__/ListProfile.test.js.snap
  __tests__/Screens/__snapshots__/LoginScreen.test.js.snap
  __tests__/Screens/__snapshots__/NewUser.test.js.snap
  __tests__/Screens/__snapshots__/NotificationScreen.test.js.snap
  __tests__/Screens/__snapshots__/ProfileManagerScreen.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
  src/Components/Absences.js
  src/Components/Form.js
  src/Components/IconButton.js
  src/Components/ScreenHeader.js
  src/Components/SideMenu.js
  src/Components/SignUpButton.js
  src/Components/routes.js
  src/Components/styles.js
  src/Screens/EditScreen.js
  src/Screens/ListProfile.js
  src/Screens/NewProfile.js
  src/Screens/NewUser.js
  src/Screens/NotificationScreen.js
  src/Screens/ProfileManagerScreen.js
  src/Screens/styles.js
  src/styles.js
Labels: 0-Developers, 1-Produto, 2-Design, 3-Task, 4-Adicionado, 5-Intermediário

#493 Fix #470 Arrumando o tamanho da ScrollView.
  src/Components/AGRButton.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#492 FIX #411_413_420_421_423 refatorando schedule
  App.js
  __mocks__/api_data.json
  __mocks__/axios.js
  __tests__/Actions/Actions.test.js
  __tests__/Components/Schedule.test.js
  __tests__/Components/ScheduleItem.test.js
  __tests__/Components/__snapshots__/AGRButton.test.js.snap
  __tests__/Components/__snapshots__/AGRInput.test.js.snap
  __tests__/Components/__snapshots__/Absences.test.js.snap
  __tests__/Components/__snapshots__/DateRangePicker.test.js.snap
  __tests__/Components/__snapshots__/ListElements.test.js.snap
  __tests__/Components/__snapshots__/Schedule.test.js.snap
  __tests__/Components/__snapshots__/ScheduleItem.test.js.snap
  __tests__/Components/__snapshots__/ScreenHeader.test.js.snap
  __tests__/Components/__snapshots__/SideMenu.test.js.snap
  __tests__/Reducers/ReducerCurrentProfile.js
  __tests__/Routes/Schedule.test.js
  __tests__/Routes/__snapshots__/Profile.test.js.snap
  __tests__/Routes/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/ProfileSchedule.test.js
  __tests__/Screens/SectorSchedule.test.js
  __tests__/Screens/WeekSchedule.test.js
  __tests__/Screens/__snapshots__/AbsencesScreen.test.js.snap
  __tests__/Screens/__snapshots__/EditScreen.test.js.snap
  __tests__/Screens/__snapshots__/ListProfile.test.js.snap
  __tests__/Screens/__snapshots__/LoginScreen.test.js.snap
  __tests__/Screens/__snapshots__/NewUser.test.js.snap
  __tests__/Screens/__snapshots__/NotificationScreen.test.js.snap
  __tests__/Screens/__snapshots__/ProfileManagerScreen.test.js.snap
  __tests__/Screens/__snapshots__/ProfileSchedule.test.js.snap
  __tests__/Screens/__snapshots__/SectorSchedule.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  package-lock.json
  src/Components/Schedule.js
  src/Components/ScheduleItem.js
  src/Components/SideMenu.js
  src/Components/routes.js
  src/Navigators/ProfileScheduleNavigation.js
  src/Navigators/ScheduleNavigation.js
  src/Navigators/SectorScheduleNavigation.js
  src/Reducers/currentProfile.js
  src/Routes/ProfileSchedule.js
  src/Routes/Schedule.js
  src/Routes/SectorSchedule.js
  src/Screens/ProfileSchedule.js
  src/Screens/SectorSchedule.js
Labels: 0-Developers, 1-Produto, 2-Feature, 3-História de Usuário, 4-Planejado, 5-Intermediário

#496 Fix #407 ligar api edit screen
  __mocks__/axios.js
  __tests__/Components/__snapshots__/AGRInput.test.js.snap
  __tests__/Components/__snapshots__/ListElements.test.js.snap
  __tests__/Components/__snapshots__/Schedule.test.js.snap
  __tests__/Components/__snapshots__/ScreenHeader.test.js.snap
  __tests__/Routes/__snapshots__/Profile.test.js.snap
  __tests__/Screens/EditScreen.test.js
  __tests__/Screens/NewUser.test.js
  __tests__/Screens/__snapshots__/AbsencesScreen.test.js.snap
  __tests__/Screens/__snapshots__/EditScreen.test.js.snap
  __tests__/Screens/__snapshots__/ListProfile.test.js.snap
  __tests__/Screens/__snapshots__/LoginScreen.test.js.snap
  __tests__/Screens/__snapshots__/NewUser.test.js.snap
  __tests__/Screens/__snapshots__/NotificationScreen.test.js.snap
  __tests__/Screens/__snapshots__/ProfileManagerScreen.test.js.snap
  __tests__/Screens/__snapshots__/ProfileSchedule.test.js.snap
  __tests__/Screens/__snapshots__/SectorSchedule.test.js.snap
  __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
  src/Screens/EditScreen.js
  src/Screens/styles.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Intermediário

#497 Fix #494 Arrumando onPress
  src/Components/IconButton.js
  src/Components/styles.js
  src/Screens/ProfileManagerScreen.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Adicionado, 5-Intermediário

#499 Fix #482 ligar criar profile com api
  __mocks__/api_data.json
  __mocks__/axios.js
  __tests__/Components/__snapshots__/Schedule.test.js.snap
  __tests__/Screens/__snapshots__/LoginScreen.test.js.snap
  __tests__/Screens/__snapshots__/ProfileSchedule.test.js.snap
  __tests__/Screens/__snapshots__/SectorSchedule.test.js.snap
  src/Screens/LoginScreen.js
  src/Screens/NewProfile.js
  src/Screens/ProfileManagerScreen.js
  src/Screens/styles.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Planejado, 5-Avançado
